// <auto-generated />
using System;
using DernekYonetim.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DernekYonetim.Migrations
{
    [DbContext(typeof(DernekYonetimContext))]
    [Migration("20260226191415_AddDogumTarihiToKayiplar")]
    partial class AddDogumTarihiToKayiplar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DernekYonetim.Models.AdminKullanicilar", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("AdminId")
                        .HasName("PK__AdminKul__719FE4E808FB369B");

                    b.HasIndex(new[] { "KullaniciAdi" }, "UQ__AdminKul__5BAE6A75D4833C62")
                        .IsUnique();

                    b.ToTable("AdminKullanicilar", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Aidatlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Aidatlar__3214EC276BCABFB7");

                    b.HasIndex("UyeId");

                    b.ToTable("Aidatlar", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.DerbisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KayitDurumu")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.HasKey("Id")
                        .HasName("PK__DerbisKa__3214EC27CA89B90C");

                    b.HasIndex("UyeId");

                    b.ToTable("DerbisKaydi", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.DernekHakkindaBolumleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DernekHa__3214EC07B60F4D3C");

                    b.HasIndex(new[] { "Slug" }, "UQ__DernekHa__BC7B5FB6DD26EB1F")
                        .IsUnique();

                    b.ToTable("DernekHakkindaBolumleri", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.EgitimMeslek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fakulte")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Meslek")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MezuniyetYili")
                        .HasColumnType("int");

                    b.Property<string>("Universite")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.HasKey("Id")
                        .HasName("PK__EgitimMe__3214EC27A5E00571");

                    b.HasIndex("UyeId");

                    b.ToTable("EgitimMeslek", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Galeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FotografYolu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("YuklemeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Galeri__3214EC272F64344B");

                    b.ToTable("Galeri", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.HaberKategorileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriAdi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__HaberKat__3214EC27DBE51158");

                    b.ToTable("HaberKategorileri", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Haberler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("FotografYolu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriID");

                    b.Property<string>("Ozet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("SlayttaGoster")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("YayimTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Haberler__3214EC277BF3D2B8");

                    b.HasIndex("KategoriId");

                    b.ToTable("Haberler", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Iletisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Iletisim__3214EC27BE87DAA3");

                    b.ToTable("Iletisim", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Kaybettiklerimiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("FotografYolu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("VefatTarihi")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Kaybetti__3214EC27EE0F9452");

                    b.ToTable("Kaybettiklerimiz", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.SosyalMedya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SosyalMe__3214EC274888AE5A");

                    b.ToTable("SosyalMedya", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Uyeler", b =>
                {
                    b.Property<int>("UyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyeId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EvlilikSoyadi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Il")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ilce")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TckimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TCKimlikNo")
                        .IsFixedLength();

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UyeNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("UyelikTarihi")
                        .HasColumnType("date");

                    b.Property<bool?>("Vefat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("UyeId")
                        .HasName("PK__Uyeler__76F7D9EF3F58ED03");

                    b.HasIndex(new[] { "UyeNo" }, "UQ__Uyeler__76F600CE67A956AD")
                        .IsUnique();

                    b.HasIndex(new[] { "TckimlikNo" }, "UQ__Uyeler__7E1935EDF83F30E2")
                        .IsUnique();

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.ZiyaretciSayaci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ToplamZiyaretci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id")
                        .HasName("PK__Ziyaretc__3214EC27B319DD08");

                    b.ToTable("ZiyaretciSayaci", (string)null);
                });

            modelBuilder.Entity("DernekYonetim.Models.Aidatlar", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uyeler", "Uye")
                        .WithMany("Aidatlars")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Aidatlar_Uyeler");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.DerbisKaydi", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uyeler", "Uye")
                        .WithMany("DerbisKaydis")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DerbisKaydi_Uyeler");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.EgitimMeslek", b =>
                {
                    b.HasOne("DernekYonetim.Models.Uyeler", "Uye")
                        .WithMany("EgitimMesleks")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EgitimMeslek_Uyeler");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("DernekYonetim.Models.Haberler", b =>
                {
                    b.HasOne("DernekYonetim.Models.HaberKategorileri", "Kategori")
                        .WithMany("Haberlers")
                        .HasForeignKey("KategoriId")
                        .HasConstraintName("FK_Haberler_Kategoriler");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("DernekYonetim.Models.HaberKategorileri", b =>
                {
                    b.Navigation("Haberlers");
                });

            modelBuilder.Entity("DernekYonetim.Models.Uyeler", b =>
                {
                    b.Navigation("Aidatlars");

                    b.Navigation("DerbisKaydis");

                    b.Navigation("EgitimMesleks");
                });
#pragma warning restore 612, 618
        }
    }
}
